name: Converter imagens para WebP

on:
  push:
    branches: [ main ]

jobs:
  convert_webp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instala cwebp
        run: sudo apt-get update && sudo apt-get install -y webp

      - name: Converte PNG/JPG -> WebP
        run: |
          find ./img \( -iname "*.png" -o -iname "*.jpg" \) -exec sh -c 'cwebp -q 80 "$0" -o "${0%.*}.webp"' {} \;

      - name: Faz commit das webp geradas
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add img/*.webp
            git commit -m "Geradas imagens WebP via Action"
            git push
          fi
